package boardgames.g3.core;

public enum LudoMoveResult{
	MOVE_VALID, MOVE_LAPSED, MOVE_NOGAMEPIECE, MOVE_INCORRECTNUMBEROFSTEPS, MOVE_VALID_INBASE_TWO_PIECES, MOVE_INVALID_INBASE_TWO_PIECES_NOT_AVAILABLE
}
